// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyMtQbnInPjmluUFxUb7-4noaUTF0uSqU',
    appId: '1:829729460255:web:e48b85e0ed1a6175bf852a',
    messagingSenderId: '829729460255',
    projectId: 'chat-app-01-22fd9',
    authDomain: 'chat-app-01-22fd9.firebaseapp.com',
    storageBucket: 'chat-app-01-22fd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNqdfCprf92IeFRHjHcCMNPKvCoftYLY',
    appId: '1:829729460255:android:eec9f0eb211a4e1fbf852a',
    messagingSenderId: '829729460255',
    projectId: 'chat-app-01-22fd9',
    storageBucket: 'chat-app-01-22fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYZdu3lxrKDLx-rIwhFgh8XriH91pmjw',
    appId: '1:829729460255:ios:dac1b7e97e4fee79bf852a',
    messagingSenderId: '829729460255',
    projectId: 'chat-app-01-22fd9',
    storageBucket: 'chat-app-01-22fd9.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYZdu3lxrKDLx-rIwhFgh8XriH91pmjw',
    appId: '1:829729460255:ios:dac1b7e97e4fee79bf852a',
    messagingSenderId: '829729460255',
    projectId: 'chat-app-01-22fd9',
    storageBucket: 'chat-app-01-22fd9.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyMtQbnInPjmluUFxUb7-4noaUTF0uSqU',
    appId: '1:829729460255:web:b71a242dee28c436bf852a',
    messagingSenderId: '829729460255',
    projectId: 'chat-app-01-22fd9',
    authDomain: 'chat-app-01-22fd9.firebaseapp.com',
    storageBucket: 'chat-app-01-22fd9.firebasestorage.app',
  );
}
